name: Feature request
description: An idea for an existing tool or a new PowerTools tool
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: idea
    attributes:
      label: What should it do?
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: What problem does it solve for you?
